#!/usr/bin/env sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

echo "==> Setup is started at…"
date "+%H:%M:%S"

echo "==> Instaling dependencies…"
yarn install

echo "==> App is now ready to go!"
date "+%H:%M:%S"

echo "==> Starting app…"
node src/app.js
